name: BuildingStaff
main: com.balugaq.buildingstaff.implementation.BuildingStaffPlugin
depend: [ Slimefun ]
authors: [ balugaq ]
website: https://github.com/balugaq/BuildingStaff
version: ${project.version}
api-version: 1.20
commands:
  buildingstaff:
    aliases: bs
    description: Building Staff base command
    usage: The Building Staff version you have installed does not seem to be compatible with your server setup. Check your console for more detailed info.
